# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welovemovies', '0002_viewing'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='rating',
            field=models.CharField(blank=True, choices=[(b'love', b'Loved it'), (b'like', b'Liked it'), (b'hate', b'Hated it'), (b'hatelike', b'Hate myself for liking it')], max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='viewing',
            name='scheduled_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
