# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welovemovies', '0003_auto_20160213_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewing',
            options={'ordering': ('scheduled_for',)},
        ),
        migrations.AddField(
            model_name='viewing',
            name='summary',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
