# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 02:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welovemovies', '0004_auto_20160213_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_days', models.CommaSeparatedIntegerField(default=(1, 1, 1, 1, 1, 1, 1), max_length=254)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.Challenge')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set([('challenge', 'owner')]),
        ),
    ]
