# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welovemovies', '0005_auto_20160214_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='week_days',
        ),
        migrations.AddField(
            model_name='schedule',
            name='friday',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='monday',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturday',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thursday',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tuesday',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='schedule',
            name='wednesday',
            field=models.IntegerField(default=1),
        ),
    ]
