# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welovemovies', '0008_moviemetadata_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewing',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
