# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welovemovies', '0010_auto_20160222_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecast',
            options={'ordering': ('ordering',)},
        ),
        migrations.AddField(
            model_name='moviecast',
            name='ordering',
            field=models.IntegerField(default=99),
        ),
    ]
