# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 11:49
#
# initial set of dates were input as "PST" but stored as "UTC", adjust them now that we have proper timezone support
#

from __future__ import unicode_literals

import datetime
from django.db import migrations


def forwards(apps, schema_editor):
    if not schema_editor.connection.alias == 'default':
        return
    Viewing = apps.get_model('welovemovies', 'Viewing')
    for viewing in Viewing.objects.all():
        if viewing.viewed_on:
            viewing.viewed_on -= datetime.timedelta(hours=8)
            viewing.save()


class Migration(migrations.Migration):

    dependencies = [
        ('welovemovies', '0011_auto_20160222_0223'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
