# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welovemovies', '0012_auto_20160304_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewing',
            name='twitter_status_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
