# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wlmuser', '0002_proxygroup'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wlmuser',
            managers=[
            ],
        ),
    ]
