# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlmuser', '0006_auto_20160311_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='wlmuser',
            name='twitter_profile_image_url',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
