# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlmuser', '0007_wlmuser_twitter_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='wlmuser',
            name='twitter_screen_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
