# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='ends',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='challenge',
            old_name='how_many',
            new_name='how_many_movies',
        ),
    ]
